### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by BeeQC** [NickleDave/tf_syllable_segmentation_annotation#12]
Hi! Not really an issue, but it would be awesome if we could have some sample data for the code to make sure everything is running as it should.

Thank you!

**Comment by NickleDave** [comment]
Hey @BeeQC , this is definitely an issue :)
Please find a list of sample data sets here:
http://hybrid-vocal-classifier.readthedocs.io/en/latest/repos.html#repos
